Docs fix
AtlassianPS/ConfluencePS pull request #182
Opened 2020-05-09 18:35 UTC by FreZZZeR

### Description

Docs fix for function Set-Attachement

### Motivation and Context

Fix bugs in documentation

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] My code follows the code style of this project.
- [ ] I have added Pester Tests that describe what my changes should do.
- [ ] I have updated the documentation accordingly.

2020-05-10 18:27 UTC, FreZZZeR commented
@lipkau , Hello!
In Azure Pipeline we have 2 errors when testing ConfluencePS functions

    Context /ConfluencePS/Private/Invoke-WebRequest.ps1
      [-] passes PSAvoidOverwritingBuiltInCmdlets 116ms
        Expected $null, but got @(1, 161).
        70:                     $BadLines | Should -Be $null
        at <ScriptBlock>, /home/vsts/work/1/s/Release/Tests/PSScriptAnalyzer.Tests.ps1: line 70

    Context /ConfluencePS/Private/Set-TlsLevel.ps1
      [-] passes PSReviewUnusedParameter 26ms
        Expected $null, but got @(6, 9).
        70:                     $BadLines | Should -Be $null
        at <ScriptBlock>, /home/vsts/work/1/s/Release/Tests/PSScriptAnalyzer.Tests.ps1: line 70


I tried using both functions on Windows 10 2004 Preview on WSL (Ubuntu 18.04, Ubuntu 20.04), and on virtual machine with Ubuntu 18.04 LTS
No one error took.
Can You explain how is your test works?

2020-05-10 19:41 UTC, FreZZZeR commented
I did not notice error messages.
_PSAvoidOverwritingBuiltInCmdlets_
Can we rename function Invoke-WebRequest to pass that test?
_PSReviewUnusedParameter_
 I repaired it in function Set-TlsLevel.ps1 setting Mandatory = $true

2020-05-10 21:49 UTC, FreZZZeR commented
@lipkau,  I fixed all error. 
I have no experience in team development using GIT.
Can you review my fixes?

2020-05-19 12:15 UTC, lipkau commented
Sorry. I missed the other PR.

2020-05-19 12:17 UTC, lipkau requested changes

2020-05-19 12:17 UTC, lipkau commented on ConfluencePS/Private/Set-TlsLevel.ps1
> +        switch ($true) {
Why are you changing this?
I don't see the benefit.

2020-05-19 12:23 UTC, FreZZZeR commented on ConfluencePS/Private/Set-TlsLevel.ps1
> +        switch ($true) {
Yes. This is need for pass psscriptanalyzer tests

Here it is:
https://dev.azure.com/AtlassianPS/ConfluencePS/_build/results?buildId=462&view=logs&j=b80c90c8-f62d-51c1-0986-3bb8359d9b6f&t=2b940409-1a40-5f39-a766-f5d254a60ca2

Text:
    Context /ConfluencePS/Private/Set-TlsLevel.ps1
      [-] passes PSReviewUnusedParameter 27ms
        Expected $null, but got @(6, 9).
        70:                     $BadLines | Should -Be $null
        at <ScriptBlock>, /home/vsts/work/1/s/Release/Tests/PSScriptAnalyzer.Tests.ps1: line 70

2020-05-19 12:25 UTC, FreZZZeR commented on ConfluencePS/Private/Set-TlsLevel.ps1
> +        switch ($true) {
If You look my comments in the PR and commit messages, You will understand me.
Thanks!

2020-05-19 12:27 UTC, FreZZZeR commented on ConfluencePS/Private/Set-TlsLevel.ps1
> +        switch ($true) {
Have I to rewrite that with [Diagnostics.CodeAnalysis.SuppressMessageAttribute()]?

2020-05-19 19:29 UTC, lipkau commented on ConfluencePS/Private/Set-TlsLevel.ps1
> +        switch ($true) {
No.
I didn't know that new rule yet.

Great job.
Thank you for the changes

2020-05-19 19:30 UTC, lipkau submitted a review, later dismissed

2020-05-19 19:35 UTC, FreZZZeR commented on ConfluencePS/Private/Set-TlsLevel.ps1
> +        switch ($true) {
I think You was right, so I repair branch for passing test without changing switch statement

2020-05-19 19:38 UTC, FreZZZeR commented
Finally, documentation was fixed. Tests can be passed.

2020-05-19 20:05 UTC, FreZZZeR reviewed
All changes has been reviewed.

2020-05-20 06:49 UTC, lipkau approved these changes

2020-05-20 06:50 UTC, merged