Exclude page body
AtlassianPS/ConfluencePS pull request #189
Opened 2021-02-27 08:14 UTC by shri5ti

### Description

`Get-Page` and `Get-ChildPage` calls fetch page content along with its metadata. A new switch parameter has been introduced in order to avoid fetching page body.

### Motivation and Context

- Reduces result size where only metadata is required

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- x[ ] My code follows the code style of this project.
- [ ] I have added Pester Tests that describe what my changes should do.
- [ x] I have updated the documentation accordingly.

2021-02-27 12:16 UTC, lipkau requested changes
Fix the integration tests and the 2 inline comments.

Rest looks fine

2021-02-27 12:16 UTC, lipkau commented on ConfluencePS/Public/Get-ChildPage.ps1
> +        if($ExcludePageBody.IsPresent){
```powershell
if ($ExcludePageBody) {
```

should do the trick, no?

2021-02-27 12:16 UTC, lipkau commented on ConfluencePS/Public/Get-Page.ps1
> +        if($ExcludePageBody.IsPresent){
```powershell
if ($ExcludePageBody) {
```

should do the trick, no?

2021-03-07 04:50 UTC, shri5ti commented
> Fix the integration tests and the 2 inline comments.
> 
> Rest looks fine

The integration tests were failing due to stale spaces on the Confluence instance. I've fixed the `New-ConfluenceSpace` test to clean these up.

2021-03-07 05:01 UTC, shri5ti reviewed
Fixed integration tests

2021-03-09 12:35 UTC, lipkau approved these changes

2021-03-09 12:35 UTC, merged